#!/bin/bash

echo "mini-launcher"

export MINI_LAUNCHER_HOME=$( cd "$( dirname "$( dirname ${BASH_SOURCE[0]})" )" && pwd )
OPENCOM_ROOT=$( cd "$( dirname "$MINI_LAUNCHER_HOME/../../micropython/opencom/." )" && pwd )

cd $OPENCOM_ROOT
make
if [[ $? != 0 ]]; then exit 1; fi

cd $MINI_LAUNCHER_HOME

# This is just wapper for execute java
source $OPENCOM_ROOT/../../machine/half/setupenv.sh

export MICROPYTHON_LAUNCHER="$MPOC_ROM/machine.py"
export MICROPYTHON_LIB="$OPENCOM_ROOT/libmicropython.so"
export CLASSPATH="$OPENCOM_ROOT/micropython.jar:$MINI_LAUNCHER_HOME"

$JAVA_HOME/bin/javac -cp $OPENCOM_ROOT/micropython.jar $MINI_LAUNCHER_HOME/MPOC/*.java

exec $JAVACMD MPOC.OpenComPythonState $MICROPYTHON_LAUNCHER $@
