#!/bin/bash
cd "$( dirname ${BASH_SOURCE[0]})"

abspath() {
  # $1 : relative filename
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}

export MPOC_ROOT=$( abspath ".." )
export MICROPY_HOME=$MPOC_ROOT/micropython/opencom
export MICROPY_MICROPYTHON=$MICROPY_HOME/micropython
export PATH=$PATH:$MICROPY_HOME

touch ./_.py.out
rm -r ./*.py.out

$MPOC_ROOT/micropython/tests/run-tests-exp.sh opencom/*.py
