#!/bin/bash

export JYTHON_HOME="env/jython2.7"
export JAVA_HOME="env/jre1.8.0_45"

export FORGE_HOME="env/forge-1.7.10"
export FORGE_LIB="$FORGE_HOME/libraries"
export MC_SERVER_JAR="$FORGE_HOME/minecraft_server.1.7.10.jar"
export OPENCOM_HOME="env/opencom"
export OPENCOM_JAR="$OPENCOM_HOME/OpenComputers-MC1.7.10-1.5.9.21-universal.jar"
export OPENCOM_JNLUA_JAR="$OPENCOM_HOME/OpenComputers-JNLua.jar"
export OPENCOM_LUAJ_JAR="$OPENCOM_HOME/OpenComputers-JNLua.jar"
export OPENCOM_RAW_LIB="$OPENCOM_HOME/lib/native.64.so"
export MPOC_ROM="../mpoc-rom"

export JAVA_MEM="-Xmx64m"
export JAVA_OPTS='-Dscala.home="$SCALA_HOME" -Djava.library.path=$OPENCOM_HOME/lib'

$JYTHON_HOME/bin/jython ./launch.py $MPOC_ROM/bios.py
